-- Базовая схема public (TZ_MARK + поля, используемые кодом). Идемпотентно.

create table if not exists public.users (
    user_id bigint primary key,
    phone text not null,
    name text not null,
    role text not null default 'client',
    created_at timestamptz not null default now()
);

create table if not exists public.services (
    id integer generated by default as identity primary key,
    name text not null unique,
    price_byn integer not null check (price_byn >= 0),
    duration_minutes integer not null check (duration_minutes > 0)
);

create table if not exists public.work_schedule (
    id integer generated by default as identity primary key,
    weekdays int[] not null,
    start_time time not null,
    end_time time not null,
    created_at timestamptz not null default now()
);

alter table public.work_schedule
    add column if not exists lunch_time time;

create table if not exists public.work_schedule_monthly (
    id bigint generated by default as identity primary key,
    month text not null,
    edit_mode text not null default 'full_month',
    schedule_json jsonb not null default '{}'::jsonb,
    updated_at timestamptz not null default now()
);

create index if not exists idx_work_schedule_monthly_month_updated
    on public.work_schedule_monthly (month, updated_at desc);

create table if not exists public.appointments (
    id bigint generated by default as identity primary key,
    user_id bigint not null references public.users (user_id) on delete cascade,
    service_id integer not null references public.services (id) on delete restrict,
    date date not null,
    start_time time not null,
    end_time time not null,
    status text not null,
    created_at timestamptz not null default now(),
    constraint appointments_start_end_check check (start_time < end_time)
);

alter table public.appointments
    drop constraint if exists appointments_status_check;

alter table public.appointments
    add constraint appointments_status_check
    check (status in ('confirmed', 'cancelled', 'completed', 'no_show'));

create index if not exists appointments_date_status_idx on public.appointments (date, status);

alter table public.appointments
    drop constraint if exists appointments_confirmed_no_overlap;

alter table public.appointments
    add constraint appointments_confirmed_no_overlap
    exclude using gist (
        tsrange(
            (date::timestamp + start_time),
            (date::timestamp + end_time),
            '[)'
        ) with &&
    )
    where (status = 'confirmed');

create table if not exists public.reminder_jobs (
    id bigint generated by default as identity primary key,
    appointment_id bigint not null references public.appointments (id) on delete cascade,
    user_id bigint not null,
    remind_type text not null,
    remind_at timestamptz not null,
    sent_at timestamptz,
    created_at timestamptz not null default now(),
    constraint reminder_jobs_unique_per_appointment_type unique (appointment_id, remind_type)
);

create index if not exists reminder_jobs_due_idx on public.reminder_jobs (remind_at);

create table if not exists public.time_blocks (
    id bigint generated by default as identity primary key,
    date date not null,
    start_time time not null,
    end_time time not null,
    master_key text,
    is_active boolean not null default true,
    created_at timestamptz not null default now(),
    constraint time_blocks_start_end_check check (start_time < end_time)
);

create index if not exists idx_time_blocks_date_master
    on public.time_blocks (date, master_key)
    where (is_active = true);
