-- Месячный график (редактор /set_schedule). Идемпотентно: можно выполнять повторно.
create table if not exists public.work_schedule_monthly (
    id bigint generated by default as identity primary key,
    month text not null,
    edit_mode text not null default 'full_month',
    schedule_json jsonb not null default '{}'::jsonb,
    updated_at timestamptz not null default now()
);

create index if not exists idx_work_schedule_monthly_month_updated
    on public.work_schedule_monthly (month, updated_at desc);
